feat: 添加axios
projects-library/vue3-music pull request #16
Opened 2023-03-08 14:11 UTC by NexusFeng

- 封装axios
- 添加环境变量

2023-03-09 06:46 UTC, Mrxtyyp requested changes
建议写上一个调用api的例子，后续都按同一格式

2023-03-09 06:46 UTC, Mrxtyyp commented on vite.config.ts
> +    server: {
这里似乎没什么必要，在baseURL有映射

2023-03-09 06:48 UTC, Mrxtyyp commented on vite.config.ts
> +    server: {
少选择了几行，server这整个代码块

2023-03-09 07:32 UTC, caosiwei97 requested changes

2023-03-09 07:32 UTC, caosiwei97 commented on vite.config.ts
> +  const env = loadEnv(mode, process.cwd(), '')
变量声明与返回语句建议空一行

2023-03-09 07:32 UTC, caosiwei97 commented on src/utils/axios.ts
> +interface Result<T> {
这个不用单独声明 Result，可以给 axios 模块写一个拓展，放到 types 目录：
```ts
declare module 'axios' {
   export interface AxiosResponse<T = any> {
        
    }
}
```

2023-03-09 07:32 UTC, caosiwei97 commented on src/utils/axios.ts
> +export default Request
这个应该导出的是单例吧，不然每个 api 文件需要 new Request 调用吗？

2023-03-09 07:59 UTC, caosiwei97 requested changes

2023-03-09 07:59 UTC, caosiwei97 commented on src/utils/axios.ts
> +        // TODO: 一些状态码处理，全局提示，例如500服务器错误
这里应该还要加上全局错误捕获处理，这样不需要在每次请求都写 try catch

2023-03-09 07:59 UTC, caosiwei97 commented on src/utils/axios.ts
> +    this.instance.interceptors.request.use(
拦截器的设置建议再拆分到方法：reqInterception resInterception，然后每个拦截器建议只针对一种场景，比如：
```
resInterception() {
 this.instance.interceptors.response.use(serilazeData) // 统一前端数据格式
 this.instance.interceptors.response.use(successHandle,errorHandle) // 成功、错误处理
}
```

2023-03-15 13:58 UTC, NexusFeng commented on vite.config.ts
> +    server: {
这个是需要的，本地要做代理

2023-03-15 13:59 UTC, NexusFeng commented on vite.config.ts
> +  const env = loadEnv(mode, process.cwd(), '')
ok

2023-03-16 07:05 UTC, Mrxtyyp approved these changes

2023-03-23 15:15 UTC, caosiwei97 approved these changes

2023-03-23 15:15 UTC, caosiwei97 commented on src/api/user.ts
> +export const getUserDetail = (uid: string) => request.get('/user/detail', { params: { uid } })
这个有测试过传泛型的时候能正确返回数据类型吗

2023-03-23 15:15 UTC, caosiwei97 commented on src/utils/axios/checkStatus.ts
> +): void {
不用显示指定 void

2023-03-23 15:15 UTC, caosiwei97 commented on src/utils/axios/checkStatus.ts
> +  switch (status) {
如果只是通过 status 拿 message ，用 map 会更好，并设置状态枚举

```ts
export const enum NetworkStatus {
   ClientError = 400
   AuthError = 401
}

export const ERROR_MESSGAE = {
  [NetworkStatus.ClientError]: 'xx'
}
```

2023-03-23 15:16 UTC, merged